first_name= input('what may be your first name:  ')
sure_name= input('what may be your sure name:   ') 
birth_year= input( 'what year you was born:    ') 
current_year= input( ' Please enter the current year:   ')
age= int( current_year)- int(birth_year)
full_name= (f' your name is  {first_name} {sure_name} and you are {age} years of age')
print(full_name)
print('--------------------------This is just a simple test in cyber_security--------------------------!!')
print("please answer the questions curectly: ")
n1= input('what is cybersecurity?       ')
print(n1.capitalize())
n2= input("what is compliance?     ")
n3= input(" list and discuss three main functions of a cybersecurity:     ") 
n4= input(' List and discuss the six domain of cybersecurity?         ')
